<a href="https://colab.research.google.com/github/AKHILESH-create/AKHILESH-create/blob/main/AI_Training10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
df=pd.read_csv("house price prediction.csv")

In [ ]:
df.head()

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.0,150.0,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.0,149.0,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2.0,150.0,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2.0,2.0,40.0,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2.0,2.0,83.0,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0


In [ ]:
df.shape

(7120, 108)

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
df.info

<bound method DataFrame.info of       bath  balcony   price  total_sqft_int  bhk  price_per_sqft  \
0      3.0      2.0  150.00          1672.0    3     8971.291866   
1      3.0      3.0  149.00          1750.0    3     8514.285714   
2      3.0      2.0  150.00          1750.0    3     8571.428571   
3      2.0      2.0   40.00          1250.0    2     3200.000000   
4      2.0      2.0   83.00          1200.0    2     6916.666667   
...    ...      ...     ...             ...  ...             ...   
7115   3.0      2.0  325.00          2900.0    3    11206.896552   
7116   3.0      1.0   84.83          1780.0    3     4765.730337   
7117   2.0      1.0   48.00           880.0    2     5454.545455   
7118   2.0      1.0   55.00          1000.0    2     5500.000000   
7119   2.0      1.0   78.00          1400.0    3     5571.428571   

      area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                                 1                        0   
1                                 0                        1   
2                                 1                        0   
3                                 1                        0   
4                                 0                        0   
...                             ...                      ...   
7115                              1                        0   
7116                              1                        0   
7117                              0                        0   
7118                              0                        0   
7119                              0                        0   

      area_typePlot  Area  availability_Ready To Move  ...  \
0                       0                           1  ...   
1                       0                           1  ...   
2                       0                           1  ...   
3                       0                           1  ...   
4                       1                           1  ...   
...                   ...                         ...  ...   
7115                    0                           1  ...   
7116                    0                           0  ...   
7117                    1                           1  ...   
7118                    1                           0  ...   
7119                    1                           0  ...   

      location_Kalena Agrahara  location_Horamavu Agara  \
0                            0                        0   
1                            0                        0   
2                            0                        0   
3                            0                        0   
4                            0                        0   
...                        ...                      ...   
7115                         0                        0   
7116                         0                        0   
7117                         0                        0   
7118                         0                        0   
7119                         0                        0   

      location_Vidyaranyapura  location_BTM 2nd Stage  \
0                           0                       0   
1                           0                       0   
2                           0                       0   
3                           0                       0   
4                           0                       0   
...                       ...                     ...   
7115                        0                       0   
7116                        0                       0   
7117                        0                       0   
7118                        0                       0   
7119                        0                       0   

      location_Hebbal Kempapura  location_Hosur Road  \
0                             0                    0   
1                             0                    0   
2                             0                    0   
3                  

In [ ]:
#'Price is our target so we have 107 input so will apply multiple linear regr.
x=df.drop('price',axis=1)
y=df['price']

In [ ]:
print("Shape of x: ", x.shape)
print("Shape of y: ", y.shape)

Shape of x:  (7120, 107)
Shape of y:  (7120,)


SPLIT DATA INTO TRAINING AND TESTING

In [ ]:
#split data into training and testing
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=66)

In [ ]:
print("Shape of x_train", x_train.shape)
print("Shape of x_test", x_test.shape)

Shape of x_train (5696, 107)
Shape of x_test (1424, 107)


In [ ]:
print("Shape of y_train", y_train.shape)
print("Shape of y_test", y_test.shape)

Shape of y_train (5696,)
Shape of y_test (1424,)


FEATURE SCALING

In [ ]:
#feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [ ]:
sc.fit(x_train)
x_train= sc.transform(x_train)
x_test= sc.transform(x_test)

ML MODEL TRAINING

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [ ]:
lr.coef_

array([ 1.64632389e+00, -1.43669569e-01,  8.24545792e+01, -1.25506109e+01,
        6.82593109e+01,  7.81247695e-01, -6.97928833e-01, -3.32786396e+00,
       -2.06276451e+00, -3.69131277e+00, -2.56063548e+00,  6.52182028e-01,
       -9.15388880e-01,  2.03522618e+00,  3.46559603e-01, -1.61708399e+00,
       -1.88361530e-01,  2.74828355e+00, -1.72149080e+00,  2.90686811e+00,
       -3.06448023e+00, -1.87606897e+00, -8.72515326e-01, -9.70691527e-02,
        1.27939774e+00,  1.92130094e+00, -5.62631239e+00, -9.32397740e-01,
       -6.36088979e-01,  1.91238674e+00, -7.14316946e-01, -5.25818779e-01,
        5.92644861e-01, -1.62703642e+00,  1.87039225e-02, -1.49912891e+00,
        4.62853323e-01,  8.36526565e-01,  3.63732993e+00,  4.18309095e-01,
        6.53629391e-01,  2.54686612e-01, -2.31537839e-01,  1.16836230e+00,
       -1.94034544e+00, -3.63130292e+00, -2.42753759e-01,  4.51485834e-02,
       -7.38360931e-01, -1.92713953e+00, -1.31412465e+00,  2.35752844e-01,
        1.27101004e+00, -

In [ ]:
lr.intercept_

np.float64(97.14672050561799)

In [ ]:
lr.score(x_test,y_test)

0.8726023171140185

In [ ]:
#predict the value of Flat or home
x_test[0,:]

array([-0.44074501,  0.55774583, -0.32720618, -0.54807827, -0.9701614 ,
        0.57626909, -0.47372946, -0.25548042,  0.5078883 , -0.1862679 ,
       -0.16104844, -0.14794369, -0.12812824, -0.12598816, -0.13770415,
       -0.12670528, -0.12454231, -0.12670528, -0.11935248, -0.11154476,
       -0.10743948, -0.11234866, -0.11314714, -0.10992018, -0.09218776,
       -0.09218776, -0.0830308 , -0.08721571, -0.09121434, -0.08721571,
       -0.08409599, -0.08514823, -0.07749158, -0.07862985, -0.07749158,
       -0.0751646 , -0.08085949, -0.07975227, -0.0739743 , -0.07028523,
       -0.07276497, -0.07749158, -0.07276497, -0.07276497, -0.0739743 ,
       -0.07153563, -0.0739743 , -0.07153563, -0.07028523, -0.06901264,
       -0.0677166 , -0.06083125, 13.97904836, -0.07028523, -0.06367332,
       -0.06901264, -0.06367332, -0.06639573, -0.06083125, -0.06083125,
       -0.06226825, -0.05785186, -0.0677166 , -0.06226825, -0.06639573,
       -0.06504853, -0.06504853, -0.06504853, -0.06367332, -0.05

In [ ]:
lr.predict([x_test[1,:]])

array([160.18889151])

In [ ]:
y_test

,price
2333,40.00
6596,135.00
1972,54.10
6588,40.00
4748,59.27
...,...
4755,260.00
558,70.00
4225,105.00
2352,115.00


In [ ]:
#prediction of test and training data
y_pred=lr.predict(x_test)
x_pred=lr.predict(x_train)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

#MAE
print("MAE Value: ", mean_absolute_error(y_test, lr.predict(x_test)), mean_squared_error(y_test, lr.predict(x_test)))

MAE Value:  16.964684267362898 912.9848815700442


In [ ]:
#MSE
print("MSE Value: ", mean_squared_error(y_test, y_pred))

MSE Value:  912.9848815700442


In [ ]:
#RMSE
print("RMSE Value: ",np.sqrt(mean_squared_error(y_test, y_pred)))

RMSE Value:  30.21563968493873


In [ ]:
#R2
from sklearn.metrics import r2_score
print("R2 Score Value: ", r2_score(y_test, y_pred))

R2 Score Value:  0.8726023171140185
